RETRY_MAX = 6
OK_CNT = 3
TIMEOUT = 20
MAINPROXYPORT = 10802
# CHECK_URL = 'https://www.youtube.com'
CHECK_URL = 'https://sukebei.nyaa.si'
INFILENAME = 'D:\\setup files\\ShadowsocksR\\gui-config.json'
OUTFILENAME = 'D:\\setup files\\ShadowsocksR\\gui-config-new.json'
MAXTHREAD = 10
